//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mozzhhevelnik.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class customers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public customers()
        {
            this.order1 = new HashSet<order>();
        }
    
        public int id { get; set; }
        [StringLength(50, ErrorMessage ="email from 5 to 50 symbols", MinimumLength =5)]
        [EmailAddress]
        public string login { get; set; }
        [StringLength(50, ErrorMessage = "name from 2 to 50 symbols", MinimumLength = 2)]
        public string contacts { get; set; }
        [StringLength(50, ErrorMessage = "contact info from 2 to 50 symbols", MinimumLength = 2)]
        public string delivery { get; set; }
        [StringLength(50, ErrorMessage = "password from 4 to 50 symbols", MinimumLength = 4)]
        public string password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order> order1 { get; set; }
    }
}
