//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mozzhhevelnik.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class disks
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public disks()
        {
            this.ordetails = new HashSet<ordetails>();
            this.supplyment = new HashSet<supplyment>();
        }
    
        public int id { get; set; }
        [StringLength(50, ErrorMessage = "name from 1 to 50 symbols", MinimumLength = 1)]
        public string name { get; set; }
        [StringLength(50, ErrorMessage = "email from 3 to 50 symbols", MinimumLength = 3)]
        public string genre { get; set; }
        [StringLength(50, ErrorMessage = "email from 1 to 50 symbols", MinimumLength = 1)]
        public string singer { get; set; }
        [Range(1300, 2050)]
        public string year { get; set; }
        [Range(0.01, 1000000)]
        public double price { get; set; }
        public byte[] cover { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ordetails> ordetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<supplyment> supplyment { get; set; }
    }
}
