//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mozzhhevelnik.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplyment
    {
        public int id { get; set; }
        public int supid { get; set; }
        public int cdid { get; set; }
        public int amount { get; set; }
        public string summ { get; set; }
    
        public virtual disks disks { get; set; }
        public virtual supplier supplier { get; set; }
    }
}
