//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mozzhhevelnik.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class supplier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public supplier()
        {
            this.supplyment = new HashSet<supplyment>();
        }
    
        public int id { get; set; }
        [StringLength(50, ErrorMessage = "name from 1 to 50 symbols", MinimumLength = 1)]
        public string name { get; set; }
        [StringLength(50, ErrorMessage = "country from 2 to 50 symbols", MinimumLength = 2)]
        public string country { get; set; }
        [StringLength(50, ErrorMessage = "description from 5 to 50 symbols", MinimumLength = 5)]
        public string desc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<supplyment> supplyment { get; set; }
    }
}
